# Generated by Django 2.1.2 on 2018-11-01 17:01

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181101_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
